include: 1_spatial.yml

target_default: 2_config

packages:
  - yaml
  - RJSONIO
  - dplyr
  - readr
  - stringr
  - glmtools


sources:
  - src/spatial_utils.R
  - src/file_utils.R

targets:
  2_config:
    depends:
      - out_data/pb0_config.json


  out_data/pb0_config.json:
    command: bundle_nml_files(target_name, 
      modeled_lake_ids, 
      nml_dir = I('../lake-temperature-process-models/2_prep/sync'))
      
